We will use "IMDB movie review sentiment classification dataset"

Dataset Description: https://keras.io/api/datasets/imdb/

This is a dataset of 25,000 movie reviews from IMDB, tagged by sentiment (positive/negative). The reviews have been preprocessed and each review is coded as a list of (whole) word indexes. For convenience, words are indexed by their overall frequency in the dataset, so that, for example, the integer "3" encodes the 3rd most frequent word in the data.

In [ ]:
!pip install keras

     ---------------------------------------- 1.7/1.7 MB 7.7 MB/s eta 0:00:00



[notice] A new release of pip is available: 23.0 -> 23.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [ ]:
!pip install tensorflow

     -------------------------------------- 266.3/266.3 MB 3.1 MB/s eta 0:00:00
     --------------------------------------- 24.4/24.4 MB 10.7 MB/s eta 0:00:00
     ---------------------------------------- 1.5/1.5 MB 13.5 MB/s eta 0:00:00
     ------------------------------------- 896.6/896.6 kB 14.1 MB/s eta 0:00:00
  Using cached google_pasta-0.2.0-py3-none-any.whl (57 kB)
     -------------------------------------- 439.2/439.2 kB 9.1 MB/s eta 0:00:00
     -------------------------------------- 126.5/126.5 kB 7.3 MB/s eta 0:00:00
  Using cached gast-0.4.0-py3-none-any.whl (9.8 kB)
  Using cached astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
     ---------------------------------------- 6.0/6.0 MB 3.7 MB/s eta 0:00:00
  Using cached opt_einsum-3.3.0-py3-none-any.whl (65 kB)
  Using cached tensorboard_data_server-0.6.1-py3-none-any.whl (2.4 kB)
  Using cached google_auth_oauthlib-0.4.6-py2.py3-none-any.whl (18 kB)
     ------------------------------------- 781.3/781.3 kB 12.4 MB/s eta 


[notice] A new release of pip is available: 23.0 -> 23.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [ ]:
import numpy
import keras
from tensorflow.keras.datasets import imdb
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import LSTM, Dropout
from tensorflow.python.keras.layers.embeddings import Embedding
from tensorflow.python.keras.layers.convolutional import Conv1D
from tensorflow.python.keras.layers.convolutional import MaxPooling1D
from tensorflow.keras.preprocessing import sequence
from tensorflow.python.keras.utils import one_hot
from tensorflow.python.keras.preprocessing.sequence import pad_sequences
from tensorflow.python.keras.layers import Flatten
# fix random seed for reproducibility;pl
numpy.random.seed(7)

ImportError: cannot import name 'one_hot' from 'tensorflow.python.keras.utils' (C:\Users\pc\Anaconda3\lib\site-packages\tensorflow\python\keras\utils\__init__.py)

In [ ]:
db=imdb.load_data()

In [ ]:
top_words = 5000
(X_train, y_train), (X_test, y_test) = imdb.load_data(num_words=top_words)

In [ ]:
len(X_train)

25000

In [ ]:
y_train

array([1, 0, 0, ..., 0, 1, 0], dtype=int64)

In [ ]:
max_review_length = 500
X_train = sequence.pad_sequences(X_train, maxlen=max_review_length)
X_test = sequence.pad_sequences(X_test, maxlen=max_review_length)

In [ ]:
X_train.shape

(25000, 500)

we will use the embedding layer which defines the first hidden layer of the network. it must specify 3 arguments:

input_dim: the size of the vocabulary in the text

output_dim: this is the size of the vector space in which each word will be immersed

input_legth: this is the size of the sequence, for example if your documents contain 100 words each then it is 100

In [ ]:
# creating tyhe model
embedding_vecor_length = 32
model = Sequential()
model.add(Embedding(top_words, embedding_vecor_length, input_length=max_review_length))
model.add(Conv1D(filters=32, kernel_size=3, padding='same', activation='relu'))
model.add(MaxPooling1D(pool_size=2))
model.add(LSTM(100))
model.add(Dense(1, activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
print(model.summary())
model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=6, batch_size=64)

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_3 (Embedding)      (None, 500, 32)           160000    
_________________________________________________________________
conv1d_1 (Conv1D)            (None, 500, 32)           3104      
_________________________________________________________________
max_pooling1d_1 (MaxPooling1 (None, 250, 32)           0         
_________________________________________________________________
lstm_1 (LSTM)                (None, 100)               53200     
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 101       
Total params: 216,405
Trainable params: 216,405
Non-trainable params: 0
_________________________________________________________________
None
Train on 25000 samples, validate on 25000 samples
Epoch 1/6
25000/25000 [==============================] - 18

In [ ]:

# evaluation
scores = model.evaluate(X_test, y_test, verbose=0)
print("Accuracy: %.2f%%" % (scores[1]*100))

Accuracy: 88.10%


## a simple example of the embedding layer

In [ ]:
docs = ['Well done!',
		'Good work',
		'Great effort',
		'nice work',
		'Excellent!',
		'Weak',
		'Poor effort!',
		'not good',
		'poor work',
		'Could have done better.']

In [ ]:
labels = [1,1,1,1,1,0,0,0,0,0]

In [ ]:
vocab_size = 50

In [ ]:
encoded_docs = [one_hot(d, vocab_size) for d in docs]

NameError: name 'one_hot' is not defined

In [ ]:
print(encoded_docs)

[[12, 43], [7, 40], [28, 36], [1, 40], [5], [20], [3, 36], [16, 7], [3, 40], [37, 26, 43, 40]]


In [ ]:
max_length = 4
padded_docs = pad_sequences(encoded_docs, maxlen=max_length, padding='post')
print(padded_docs)

[[12 43  0  0]
 [ 7 40  0  0]
 [28 36  0  0]
 [ 1 40  0  0]
 [ 5  0  0  0]
 [20  0  0  0]
 [ 3 36  0  0]
 [16  7  0  0]
 [ 3 40  0  0]
 [37 26 43 40]]


We are now ready to define our Embedding layer as part of our model.

The embedding has a vocabulary of 50 and an entry length of 4. We will choose a small embedding space of 8 dimensions.

The model is a simple binary classification model. It is important to note that the output of the Embedding layer will be 4 vectors of 8 dimensions each, one for each word. We flatten it (the flatten layer) into a 32-element vector to pass it to the Dense output layer.

In [ ]:
model = Sequential()
model.add(Embedding(vocab_size, 8, input_length=max_length))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))
# compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
# summarize the model
print(model.summary())

Model: "sequential_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_5 (Embedding)      (None, 4, 8)              400       
_________________________________________________________________
flatten (Flatten)            (None, 32)                0         
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 33        
Total params: 433
Trainable params: 433
Non-trainable params: 0
_________________________________________________________________
None


In [ ]:
model.fit(padded_docs, labels, epochs=50, verbose=0)

In [ ]:
loss, accuracy = model.evaluate(padded_docs, labels, verbose=0)
print('Accuracy: %f' % (accuracy*100))

Accuracy: 100.000000


## To Do:

1. Try the same thing on Google reviews dataset ( the file is given in the lab directory)
2. try to change the embedding representation using Glove and Skipgram

In [2]:

# Step 1: Download GloVe word embeddings

# Replace 'glove.6B.100d.txt' with the appropriate GloVe file name and path
!wget http://nlp.stanford.edu/data/glove.6B.zip
!unzip glove.6B.zip

--2023-06-17 18:46:03--  http://nlp.stanford.edu/data/glove.6B.zip
Resolving nlp.stanford.edu (nlp.stanford.edu)... 171.64.67.140
Connecting to nlp.stanford.edu (nlp.stanford.edu)|171.64.67.140|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://nlp.stanford.edu/data/glove.6B.zip [following]
--2023-06-17 18:46:03--  https://nlp.stanford.edu/data/glove.6B.zip
Connecting to nlp.stanford.edu (nlp.stanford.edu)|171.64.67.140|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://downloads.cs.stanford.edu/nlp/data/glove.6B.zip [following]
--2023-06-17 18:46:03--  https://downloads.cs.stanford.edu/nlp/data/glove.6B.zip
Resolving downloads.cs.stanford.edu (downloads.cs.stanford.edu)... 171.64.64.22
Connecting to downloads.cs.stanford.edu (downloads.cs.stanford.edu)|171.64.64.22|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 862182613 (822M) [application/zip]
Saving to: ‘glove.6B.zip.2’

gl

In [4]:
df

userName                                          userImage  \
0          Andrew Thomas  https://lh3.googleusercontent.com/a-/AOh14GiHd...   
1           Craig Haines  https://lh3.googleusercontent.com/-hoe0kwSJgPQ...   
2          steven adkins  https://lh3.googleusercontent.com/a-/AOh14GiXw...   
3       Lars Panzerbjørn  https://lh3.googleusercontent.com/a-/AOh14Gg-h...   
4          Scott Prewitt  https://lh3.googleusercontent.com/-K-X1-YsVd6U...   
...                  ...                                                ...   
15741          Tammy Kay  https://lh3.googleusercontent.com/a-/AOh14GhYP...   
15742          Ysm Johan  https://lh3.googleusercontent.com/a-/AOh14Ggmd...   
15743      casey dearden  https://lh3.googleusercontent.com/a-/AOh14Gg2U...   
15744     Jerry G Tamate  https://lh3.googleusercontent.com/a-/AOh14GiTP...   
15745  Ahmed elsalamouni  https://lh3.googleusercontent.com/-9QSxVUhCoDI...   

                                                 content  score  \
0      Update: After getting a response from the deve...      1   
1      Used it for a fair amount of time without any ...      1   
2      Your app sucks now!!!!! Used to be good but no...      1   
3      It seems OK, but very basic. Recurring tasks n...      1   
4      Absolutely worthless. This app runs a prohibit...      1   
...                                                  ...    ...   
15741  I believe that this is by far the best app wit...      5   
15742                       It sometimes crashes a lot!!      5   
15743                         Works well for what I need      5   
15744                                           Love it.      5   
15745  Really amazing and helped me sooo much just i ...      5   

       thumbsUpCount reviewCreatedVersion                   at  \
0                 21             4.17.0.3  2020-04-05 22:25:57   
1                 11             4.17.0.3  2020-04-04 13:40:01   
2                 17             4.17.0.3  2020-04-01 16:18:13   
3                192             4.17.0.2  2020-03-12 08:17:34   
4                 42             4.17.0.2  2020-03-14 17:41:01   
...              ...                  ...                  ...   
15741              0                  NaN  2018-02-17 06:09:03   
15742              0                4.3.7  2018-02-15 10:45:22   
15743              0                4.3.7  2018-02-09 18:40:37   
15744              0                  NaN  2018-02-06 12:36:17   
15745              6                4.3.7  2018-02-04 22:57:09   

                                            replyContent            repliedAt  \
0      According to our TOS, and the term you have ag...  2020-04-05 15:10:24   
1      It sounds like you logged in with a different ...  2020-04-05 15:11:35   
2      This sounds odd! We are not aware of any issue...  2020-04-02 16:05:56   
3      We do offer this option as part of the Advance...  2020-03-15 06:20:13   
4      We're sorry you feel this way! 90% of the app ...  2020-03-15 23:45:51   
...                                                  ...                  ...   
15741                                                NaN                  NaN   
15742                                                NaN                  NaN   
15743                                                NaN                  NaN   
15744                                                NaN                  NaN   
15745                                                NaN                  NaN   

           sortOrder              appId  
0      most_relevant          com.anydo  
1      most_relevant          com.anydo  
2      most_relevant          com.anydo  
3      most_relevant          com.anydo  
4      most_relevant          com.anydo  
...              ...                ...  
15741         newest  com.appxy.planner  
15742         newest  com.appxy.planner  
15743         newest  com.appxy.planner  
15744         newest  com.appxy.planner  
15745         newest  com.appxy.pl

In [6]:
import pandas as pd
from sklearn.model_selection import train_test_split
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Flatten, Dense


# Step 2: Load the Google reviews dataset

# Replace 'path_to_csv' with the actual path to your Google reviews dataset
df = pd.read_csv('reviews.csv')

# Preprocess the data (tokenization, lowercase conversion, etc.)
# Replace this with your own preprocessing steps

# Split the data into training and test sets
# Adjust the test_size and random_state as needed
X_train, X_test, y_train, y_test = train_test_split(df['content'], df['score'], test_size=0.2, random_state=42)
import numpy as np
# Step 3: Tokenize the text data

top_words = 5000
tokenizer = Tokenizer(num_words=top_words)
tokenizer.fit_on_texts(X_train)

X_train_sequences = tokenizer.texts_to_sequences(X_train)
X_test_sequences = tokenizer.texts_to_sequences(X_test)

# Pad sequences to have the same length
max_sequence_length = max(len(sequence) for sequence in X_train_sequences)
X_train_padded = pad_sequences(X_train_sequences, maxlen=max_sequence_length)
X_test_padded = pad_sequences(X_test_sequences, maxlen=max_sequence_length)

# Step 4: Create an embedding matrix using GloVe word embeddings

embedding_dim = 100  # Change this to the appropriate embedding dimension based on the GloVe file used

# Create a dictionary mapping words to their corresponding GloVe vectors
word_to_vec = {}
with open('glove.6B.100d.txt', encoding='utf8') as f:
    for line in f:
        values = line.split()
        word = values[0]
        vector = np.array(values[1:], dtype='float32')
        word_to_vec[word] = vector

# Create an embedding matrix
vocab_size = len(tokenizer.word_index) + 1
embedding_matrix = np.zeros((vocab_size, embedding_dim))
for word, i in tokenizer.word_index.items():
    if word in word_to_vec:
        embedding_matrix[i] = word_to_vec[word]

# Step 5: Build and train a model using Skipgram embedding representation

model = Sequential()
model.add(Embedding(vocab_size, embedding_dim, weights=[embedding_matrix], input_length=max_sequence_length, trainable=False))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

# Compile and train the model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X_train_padded, y_train, validation_data=(X_test_padded, y_test), epochs=10, batch_size=128)


Epoch 1/10
99/99 [==============================] - 1s 6ms/step - loss: -72.5791 - accuracy: 0.1612 - val_loss: -154.2550 - val_accuracy: 0.1632
Epoch 2/10
99/99 [==============================] - 1s 6ms/step - loss: -221.3691 - accuracy: 0.1624 - val_loss: -309.2115 - val_accuracy: 0.1632
Epoch 3/10
99/99 [==============================] - 1s 8ms/step - loss: -370.2920 - accuracy: 0.1624 - val_loss: -464.4019 - val_accuracy: 0.1632
Epoch 4/10
99/99 [==============================] - 1s 7ms/step - loss: -519.1991 - accuracy: 0.1624 - val_loss: -619.5007 - val_accuracy: 0.1632
Epoch 5/10
99/99 [==============================] - 1s 6ms/step - loss: -668.3745 - accuracy: 0.1624 - val_loss: -775.2603 - val_accuracy: 0.1632
Epoch 6/10
99/99 [==============================] - 1s 6ms/step - loss: -817.3159 - accuracy: 0.1624 - val_loss: -930.2280 - val_accuracy: 0.1632
Epoch 7/10
99/99 [==============================] - 0s 5ms/step - loss: -966.4356 - accuracy: 0.1624 - val_loss: -1085.8774 -